In [6]:
# Importamos las librerías necesarias
import pandas as pd
import numpy as np
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
# Para imputación de nulos usando métodos estadísticos avanzados
from sklearn.impute import SimpleImputer 
from sklearn.experimental import enable_iterative_imputer # Necesario para IterativeImputer
from sklearn.impute import IterativeImputer 
from sklearn.impute import KNNImputer

In [10]:
df_hr_attrition_yes = pd.read_csv("df_hr_attrition_yes.csv")
df_hr_attrition_yes.head(2)

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
1,37.0,Yes,rarely,research_&_development,2,2,other,4,4,Male,92,2,1,laboratory_technician,3.0,single,2090.0,6,Yes,15,3,2,0,7,3.0,3,0,0,0,0.0

In [13]:
def exploracion_basica(df):
    print(f"Las dos primeras filas son:")
    display(df.head(2))
    print("=" * 50)
    print(f"Las dos últimas filas son:")
    display(df.tail(2))
    print("=" * 50)
    print(f"Las dos filas aleatorias son:")
    display(df.sample(2)) 
    print("=" * 50)
    print(f"Información sobre DataFrame:")
    print(df.info())
    print("=" * 50)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas.")
    return df

In [14]:
df_hr_attrition_yes = exploracion_basica(df_hr_attrition_yes)

Las dos primeras filas son:

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
0,41.0,Yes,rarely,sales,1,2,life_sciences,1,2,Female,94,3,2,sales_executive,4.0,single,5993.0,8,Yes,11,3,1,0,8,0.0,1,6,4,0,5.0
1,37.0,Yes,rarely,research_&_development,2,2,other,4,4,Male,92,2,1,laboratory_technician,3.0,single,2090.0,6,Yes,15,3,2,0,7,3.0,3,0,0,0,0.0

==================================================
Las dos últimas filas son:

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
235,50.0,Yes,frequently,sales,1,4,life_sciences,2044,2,Male,94,3,2,sales_executive,3.0,divorced,6728.0,7,No,12,3,4,2,12,3.0,3,6,3,0,1.0
236,50.0,Yes,rarely,NaN,28,3,marketing,2055,4,Male,39,2,3,sales_executive,1.0,divorced,10854.0,4,Yes,13,3,2,1,20,NaN,3,3,2,2,0.0

==================================================
Las dos filas aleatorias son:

,age,attrition,business_travel,department,distance_from_home,education,education_field,employee_number,environment_satisfaction,gender,hourly_rate,job_involvement,job_level,job_role,job_satisfaction,marital_status,monthly_income,num_companies_worked,over_time,percent_salary_hike,performance_rating,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager
183,40.0,Yes,rarely,research_&_development,9,4,life_sciences,1534,4,Male,86,3,1,laboratory_technician,1.0,single,2018.0,3,No,14,3,2,0,15,3.0,1,5,4,1,0.0
212,NaN,Yes,frequently,research_&_development,9,4,life_sciences,1807,4,Male,93,3,2,laboratory_technician,1.0,married,5346.0,4,No,17,3,3,1,11,3.0,2,7,1,0,7.0

==================================================
Información sobre DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 237 entries, 0 to 236
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         220 non-null    float64
 1   attrition                   237 non-null    object
 2   business_travel             214 non-null    object
 3   department                  227 non-null    object
 4   distance_from_home          237 non-null    int64
 5   education                   237 non-null    int64
 6   education_field             231 non-null    object
 7   employee_number             237 non-null    int64
 8   environment_satisfaction    237 non-null    int64
 9   gender                      237 non-null    object
 10  hourly_rate                 237 non-null    int64
 11  job_involvement             237 non-null    int64
 12  job_level                   237 non-null    int64
 13  job_role                    237 non-null    object
 14  job_satisfaction            231 non-null    float64
 15  marital_status              221 non-null    object
 16  monthly_income              233 non-null    float64
 17  num_companies_worked        237 non-null    int64
 18  over_time                   229 non-null    object
 19  percent_salary_hike         237 non-null    int64
 20  performance_rating          237 non-null    int64
 21  relationship_satisfaction   237 non-null    int64
 22  stock_option_level          237 non-null    int64
 23  total_working_years         237 non-null    int64
 24  training_times_last_year    225 non-null    float64
 25  work_life_balance           237 non-null    int64
 26  years_at_company            237 non-null    int64
 27  years_in_current_role       237 non-null    int64
 28  years_since_last_promotion  237 non-null    int64
 29  years_with_curr_manager     211 non-null    float64
dtypes: float64(5), int64(17), object(8)
memory usage: 55.7+ KB
None
==================================================
El dataframe tiene 237 filas y 30 columnas.

In [11]:
def analisis_descriptivo(df):
    print("🔹 NUMÉRICAS")
    display(df.describe(include = "number").T)
    
    print("\n🔹 CATEGÓRICAS")
    display(df.describe(include="object").T)

In [12]:
analisis_descriptivo(df_hr_attrition_yes)

🔹 NUMÉRICAS

,count,mean,std,min,25%,50%,75%,max
age,220.0,33.677273,9.710439,18.0,28.0,32.0,39.0,58.0
distance_from_home,237.0,10.632911,8.452525,1.0,3.0,9.0,17.0,29.0
education,237.0,2.839662,1.008244,1.0,2.0,3.0,4.0,5.0
employee_number,237.0,1010.345992,580.750572,1.0,514.0,1017.0,1486.0,2055.0
environment_satisfaction,237.0,2.464135,1.169791,1.0,1.0,3.0,4.0,4.0
hourly_rate,237.0,65.573840,20.099958,31.0,50.0,66.0,84.0,100.0
job_involvement,237.0,2.518987,0.773405,1.0,2.0,3.0,3.0,4.0
job_level,237.0,1.637131,0.940594,1.0,1.0,1.0,2.0,5.0
job_satisfaction,231.0,2.467532,1.118047,1.0,1.0,3.0,3.0,4.0
monthly_income,233.0,4754.708155,3630.120692,1009.0,2367.0,3202.0,5828.0,19859.0
num_companies_worked,237.0,2.940928,2.678519,0.0,1.0,1.0,5.0,9.0
percent_salary_hike,237.0,15.097046,3.770294,11.0,12.0,14.0,17.0,25.0
performance_rating,237.0,3.156118,0.363735,3.0,3.0,3.0,3.0,4.0
relationship_satisfaction,237.0,2.599156,1.125437,1.0,2.0,3.0,4.0,4.0
stock_option_level,237.0,0.527426,0.856361,0.0,0.0,0.0,1.0,3.0
total_working_years,237.0,8.244726,7.169204,0.0,3.0,7.0,10.0,40.0
training_times_last_year,225.0,2.608889,1.266996,0.0,2.0,2.0,3.0,6.0
work_life_balance,237.0,2.658228,0.816453,1.0,2.0,3.0,3.0,4.0
years_at_company,237.0,5.130802,5.949984,0.0,1.0,3.0,7.0,40.0
years_in_current_role,237.0,2.902954,3.174827,0.0,0.0,2.0,4.0,15.0
years_since_last_promotion,237.0,1.945148,3.153077,0.0,0.0,1.0,2.0,15.0
years_with_curr_manager,211.0,2.985782,3.185501,0.0,0.0,2.0,6.0,14.0

🔹 CATEGÓRICAS

                count unique                     top freq
attrition         237      1                     Yes  237
business_travel   214      3                  rarely  137
department        227      3  research_&_development  126
education_field   231      6           life_sciences   87
gender            237      2                    Male  150
job_role          237      9   laboratory_technician   62
marital_status    221      3                  single  112
over_time         229      2                     Yes  125

In [ ]:
# Conclusiones del análisis descriptivo (variables categóricas):
# - La mayoría de los empleados que han dejado la empresa (attrition = Yes) son hombres (84.8%).
# - La mayoría raramente viajan, son de dpto de research & development
# - La mayoría son solteros, hacen horas extra y trabajan en laboratorio tecnico.
# - La maypría han estudiado life_sciences

In [ ]:
# num_companies_worked	y total_working_years pueden tener relacion,
# ya que ambas variables se refieren a la experiencia laboral del empleado.
# Es posible que un empleado que ha trabajado en muchas empresas
# también tenga muchos años de experiencia laboral.
# Sin embargo, no es una regla estricta, ya que un empleado podría haber trabajado
# en pocas empresas pero haber acumulado muchos años de experiencia en esas empresas.
# Por lo tanto, aunque estas variables pueden estar relacionadas, no necesariamente lo están
# en todos los casos.
# Sería útil analizar la correlación entre estas variables
# para entender mejor su relación en el contexto de este dataset específico.